<?php
/**
 * Create/Edit Learning Path Item Form - Test Bank LMS
 * Renders a form to add a document or link to a course's learning path,
 * select its prerequisites, and specify if it's required.
 */
$pageTitle = $formTitle . ' - ' . htmlspecialchars($course['title']);
include __DIR__ . '/../layout_header.php';
?>

<div class="mb-4" id="form-header-container">
    <a href="index.php?route=admin/learning-path&action=list&course_id=<?php echo $courseId; ?>" class="text-decoration-none text-muted small d-flex align-items-center gap-1 mb-2">
        <i data-lucide="arrow-left" size="14"></i> Back to Learning Path Sequence
    </a>
    <h3 class="display-font fw-bold text-dark mb-1"><?php echo $formTitle; ?></h3>
    <p class="text-muted small">Course: <strong><?php echo htmlspecialchars($course['title']); ?></strong></p>
</div>

<?php if (isset($errors['form'])): ?>
    <div class="alert alert-danger font-sans small mb-4" role="alert">
        <i data-lucide="alert-circle" size="16" class="me-1 text-danger"></i>
        <?php echo htmlspecialchars($errors['form']); ?>
    </div>
<?php endif; ?>

<div class="row" id="form-body-container">
    <div class="col-lg-8 col-md-10">
        <div class="card border-0 shadow-sm">
            <div class="card-body p-4">
                <form action="<?php echo $actionUrl; ?>" method="POST" id="learning-path-form">
                    <input type="hidden" name="csrf_token" value="<?php echo $csrfToken; ?>">

                    <?php if ($isEdit): ?>
                        <!-- Static info display in edit mode -->
                        <div class="mb-4">
                            <label class="form-label fw-semibold text-muted small uppercase">Selected Milestone Content</label>
                            <div class="p-3 bg-light rounded border">
                                <div class="d-flex align-items-center gap-2 mb-1">
                                    <?php if ($itemType === 'document'): ?>
                                        <span class="badge bg-danger text-white py-1 px-2 font-sans" style="font-size: 0.7rem;">Document</span>
                                    <?php elseif ($itemType === 'link'): ?>
                                        <span class="badge bg-info text-white py-1 px-2 font-sans" style="font-size: 0.7rem;">Link</span>
                                    <?php elseif ($itemType === 'quiz'): ?>
                                        <span class="badge bg-primary text-white py-1 px-2 font-sans" style="font-size: 0.7rem;">Quiz</span>
                                    <?php endif; ?>
                                    <strong class="text-dark font-sans"><?php echo htmlspecialchars($item['title']); ?></strong>
                                </div>
                                <span class="text-muted small font-mono">Reference Item ID: <?php echo $itemId; ?></span>
                            </div>
                        </div>
                    <?php else: ?>
                        <!-- Content selector in creation mode -->
                        <div class="row mb-3">
                            <div class="col-md-6 mb-3 mb-md-0">
                                <label for="item_type" class="form-label fw-bold small text-dark">1. Content Type</label>
                                <select class="form-select <?php echo isset($errors['item_type']) ? 'is-invalid' : ''; ?>" id="item_type" name="item_type" required>
                                    <option value="document" <?php echo ($itemType === 'document') ? 'selected' : ''; ?>>Document</option>
                                    <option value="link" <?php echo ($itemType === 'link') ? 'selected' : ''; ?>>External Resource Link</option>
                                    <option value="quiz" <?php echo ($itemType === 'quiz') ? 'selected' : ''; ?>>Quiz / Exam</option>
                                </select>
                                <?php if (isset($errors['item_type'])): ?>
                                    <div class="invalid-feedback"><?php echo htmlspecialchars($errors['item_type']); ?></div>
                                <?php endif; ?>
                            </div>

                            <div class="col-md-6">
                                <label for="item_id" class="form-label class-item-label fw-bold small text-dark">2. Specific Resource</label>
                                <select class="form-select <?php echo isset($errors['item_id']) ? 'is-invalid' : ''; ?>" id="item_id" name="item_id" required>
                                    <!-- Dynamic elements generated by JS -->
                                </select>
                                <?php if (isset($errors['item_id'])): ?>
                                    <div class="invalid-feedback"><?php echo htmlspecialchars($errors['item_id']); ?></div>
                                <?php endif; ?>
                            </div>
                        </div>

                        <!-- Quiz Placeholder Alert Notice -->
                        <div id="quiz-help-message" class="alert alert-info font-sans small d-none mb-3">
                            <i data-lucide="info" size="14" class="me-1.5 text-info"></i>
                            <strong>Phase 3/4 Note:</strong> The quizzes/exams feature does not exist yet. You can see the 'quiz' option is present in the database types and UI, but options are intentionally empty for this step. No quiz records exist to select.
                        </div>
                    <?php endif; ?>

                    <!-- Prerequisite Selector (Same for both Create/Edit) -->
                    <div class="mb-3">
                        <label for="prerequisite_item_id" class="form-label fw-bold small text-dark">Prerequisite Step (Optional)</label>
                        <select class="form-select <?php echo isset($errors['prerequisite_item_id']) ? 'is-invalid' : ''; ?>" id="prerequisite_item_id" name="prerequisite_item_id">
                            <option value="">None (Unlock Immediately)</option>
                            <?php foreach ($possiblePrerequisites as $pOption): ?>
                                <option value="<?php echo $pOption['id']; ?>" <?php echo ($prerequisiteItemId == $pOption['id']) ? 'selected' : ''; ?>>
                                    Step <?php echo htmlspecialchars($pOption['order_index'] + 1); ?>: <?php echo htmlspecialchars($pOption['title']); ?> (<?php echo ucfirst($pOption['item_type']); ?>)
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <small class="text-muted d-block mt-1 font-sans" style="font-size: 0.75rem;">
                            Students must fully complete the chosen prerequisite step before they can access this item.
                        </small>
                        <?php if (isset($errors['prerequisite_item_id'])): ?>
                            <div class="invalid-feedback"><?php echo htmlspecialchars($errors['prerequisite_item_id']); ?></div>
                        <?php endif; ?>
                    </div>

                    <!-- Required Status checkbox -->
                    <div class="mb-4">
                        <div class="form-check form-switch p-0 ps-5">
                            <input class="form-check-input ms-n5" type="checkbox" role="switch" id="is_required" name="is_required" value="1" <?php echo ($isRequired) ? 'checked' : ''; ?>>
                            <label class="form-check-label fw-semibold text-dark small" for="is_required">Required to Unlock Next Steps</label>
                            <small class="text-muted d-block font-sans" style="font-size: 0.75rem;">
                                If checked, this milestone acts as a gate and must be marked complete to satisfy dependency unlocks.
                            </small>
                        </div>
                    </div>

                    <div class="d-flex justify-content-end gap-2 border-top pt-3">
                        <a href="index.php?route=admin/learning-path&action=list&course_id=<?php echo $courseId; ?>" class="btn btn-light border font-sans">Cancel</a>
                        <button type="submit" class="btn btn-primary font-sans px-4">
                            <i data-lucide="save" size="16" class="me-1"></i> Save Path Item
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php if (!$isEdit): ?>
<script>
// Dynamic drop down binding list data passed from controller
const documents = <?php echo json_encode($documents); ?>;
const links = <?php echo json_encode($links); ?>;

const itemTypeSelect = document.getElementById('item_type');
const itemIdSelect = document.getElementById('item_id');
const quizHelp = document.getElementById('quiz-help-message');

function updateItemDropdown() {
    const selectedType = itemTypeSelect.value;
    itemIdSelect.innerHTML = '';
    quizHelp.classList.add('d-none');

    let options = [];
    if (selectedType === 'document') {
        options = documents;
    } else if (selectedType === 'link') {
        options = links;
    } else if (selectedType === 'quiz') {
        quizHelp.classList.remove('d-none');
    }

    if (options.length === 0) {
        const opt = document.createElement('option');
        opt.value = '';
        opt.textContent = selectedType === 'quiz' ? '-- Quizzes Not Built Yet --' : '-- No Available Unused Content --';
        itemIdSelect.appendChild(opt);
        itemIdSelect.disabled = true;
    } else {
        itemIdSelect.disabled = false;
        const placeholder = document.createElement('option');
        placeholder.value = '';
        placeholder.textContent = '-- Select Content Item --';
        placeholder.required = true;
        itemIdSelect.appendChild(placeholder);

        options.forEach(item => {
            const opt = document.createElement('option');
            opt.value = item.id;
            opt.textContent = item.title;
            itemIdSelect.appendChild(opt);
        });
    }
}

itemTypeSelect.addEventListener('change', updateItemDropdown);
// Execute on first page render
updateItemDropdown();
</script>
<?php endif; ?>

<?php include __DIR__ . '/../layout_footer.php'; ?>
